const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={task:null,assets:[],selected:null,tool:'select',image:null,zoom:1,panX:0,panY:0,drag:null,stroke:[],previewBg:'checker'};
async function api(url,options={}){const r=await fetch(url,options);let body;try{body=await r.json()}catch{body=null}if(!r.ok)throw new Error(body?.message||`${r.status} ${r.statusText}`);return body}
function message(text='',ok=false){const e=$('#message');e.textContent=text;e.style.color=ok?'#178148':'#d73535'}
function revision(){return state.task?.revision}
async function init(){try{await api('/health');$('#health').textContent='API 正常'}catch(e){$('#health').textContent='API 不可用';message(e.message)}bind()}
function bind(){
  $('#uploadForm').addEventListener('submit',upload);$('#undo').onclick=()=>edit('/undo',{});$('#redo').onclick=()=>edit('/redo',{});
  $('#zoomIn').onclick=()=>{state.zoom=Math.min(5,state.zoom*1.2);draw()};$('#zoomOut').onclick=()=>{state.zoom=Math.max(.2,state.zoom/1.2);draw()};$('#fit').onclick=()=>{state.zoom=1;state.panX=state.panY=0;draw()};
  $$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.tool=b.dataset.tool;state.stroke=[];draw()});
  $$('.preview-bg button').forEach(b=>b.onclick=()=>{$$('.preview-bg button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.previewBg=b.dataset.bg;updatePreview()});
  $('#brushSize').oninput=e=>$('#brushSizeOut').value=e.target.value;$('#applyStroke').onclick=applyStroke;$('#saveBbox').onclick=saveBbox;
  $('#merge').onclick=merge;$('#delete').onclick=removeAsset;$('#moveUp').onclick=()=>move(-1);$('#moveDown').onclick=()=>move(1);$('#rename').onclick=rename;$('#export').onclick=exportFiles;
  const c=$('#stage');c.addEventListener('contextmenu',e=>e.preventDefault());c.addEventListener('pointerdown',pointerDown);c.addEventListener('pointermove',pointerMove);c.addEventListener('pointerup',pointerUp);c.addEventListener('pointercancel',pointerUp);c.addEventListener('wheel',e=>{e.preventDefault();state.zoom=Math.max(.2,Math.min(5,state.zoom*(e.deltaY<0?1.1:.9)));draw()},{passive:false});
}
async function upload(e){e.preventDefault();message();const data=new FormData(e.target);if(!data.get('canvasSize'))data.delete('canvasSize');for(const name of ['includeZip','useRmbg','useSam31'])data.set(name,e.target.elements[name].checked?'true':'false');$('#progressBox').hidden=false;$('#progress').value=0;try{state.task=await api('/api/asset-extraction/tasks',{method:'POST',body:data});await poll()}catch(err){message(err.message)}}
async function poll(){for(;;){state.task=await api(`/api/asset-extraction/tasks/${state.task.task_id}`);$('#progress').value=state.task.progress;$('#progressText').textContent=`${state.task.progress}% · ${state.task.stage}`;if(state.task.status==='completed')break;if(state.task.status==='failed'||state.task.status==='cancelled')throw new Error(state.task.error?.message||state.task.status);await new Promise(r=>setTimeout(r,250))}await loadWorkspace()}
async function loadWorkspace(){const id=state.task.task_id;const data=await api(`/api/asset-extraction/tasks/${id}/assets`);state.assets=data.assets;state.selected=state.assets.find(a=>a.id===state.selected?.id)||state.assets[0]||null;state.image=await loadImage(`/api/asset-extraction/tasks/${id}/source?rev=${revision()}`);$('#workspace').hidden=false;$('#exportPanel').hidden=false;$('#backgroundInfo').textContent=`背景：${state.task.backgroundType} · 置信度 ${Math.round((state.task.backgroundConfidence||0)*100)}%${(state.task.backgroundConfidence||0)<.6?' · 需要人工确认':''}`;renderAssets();selectAsset(state.selected?.id);draw();message(`已提取 ${state.assets.length} 个素材`,true)}
function loadImage(src){return new Promise((resolve,reject)=>{const i=new Image;i.onload=()=>resolve(i);i.onerror=reject;i.src=src})}
function renderAssets(){const root=$('#assetList');root.innerHTML='';for(const a of state.assets){const card=document.createElement('div');card.className=`asset-card ${a.id===state.selected?.id?'selected':''} ${a.status==='needs-review'?'review':''}`;card.dataset.id=a.id;card.innerHTML=`<div class="asset-thumb"><img src="/api/asset-extraction/tasks/${state.task.task_id}/assets/${a.id}/preview?background=checker&rev=${revision()}" alt=""></div><input type="checkbox" aria-label="选择合并"><div><b>${a.file.split('/').pop()}</b><br><small>#${a.index} · ${Math.round(a.confidence*100)}% · ${a.status}</small></div>`;card.onclick=e=>{if(e.target.type!=='checkbox')selectAsset(a.id)};root.append(card)}}
function selectAsset(id){state.selected=state.assets.find(a=>a.id===id)||null;renderAssets();const a=state.selected;if(!a)return;$('#bx').value=a.x;$('#by').value=a.y;$('#bw').value=a.width;$('#bh').value=a.height;$('#renameInput').value=a.file.split('/').pop();$('#downloadAsset').href=`/api/asset-extraction/tasks/${state.task.task_id}/assets/${a.id}/download`;updatePreview();draw()}
function updatePreview(){if(!state.selected)return;$('#assetPreview').src=`/api/asset-extraction/tasks/${state.task.task_id}/assets/${state.selected.id}/preview?background=${state.previewBg}&rev=${revision()}`}
function canvasPoint(e){const c=$('#stage'),r=c.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*c.width,y:(e.clientY-r.top)/r.height*c.height}}
function imagePoint(e){const p=canvasPoint(e),t=transform();return{x:Math.round((p.x-t.x)/t.scale),y:Math.round((p.y-t.y)/t.scale)}}
function transform(){const c=$('#stage'),fit=Math.min((c.width-20)/state.image.width,(c.height-20)/state.image.height);const scale=fit*state.zoom;return{scale,x:(c.width-state.image.width*scale)/2+state.panX,y:(c.height-state.image.height*scale)/2+state.panY}}
function pointerDown(e){if(!state.image)return;$('#stage').setPointerCapture(e.pointerId);const p=imagePoint(e);state.drag={start:p,last:p};if(['add','erase'].includes(state.tool))state.stroke=[p]}
function pointerMove(e){if(!state.drag)return;const p=imagePoint(e);if(['add','erase'].includes(state.tool)){state.stroke.push(p)}else if(state.tool==='select'&&e.buttons===2){state.panX+=p.x-state.drag.last.x;state.panY+=p.y-state.drag.last.y}state.drag.last=p;draw()}
async function pointerUp(e){if(!state.drag)return;const end=imagePoint(e),start=state.drag.start;state.drag=null;if(state.tool==='select'){const hit=[...state.assets].reverse().find(a=>end.x>=a.x&&end.x<=a.x+a.width&&end.y>=a.y&&end.y<=a.y+a.height);if(hit)selectAsset(hit.id)}else if(state.tool==='split'&&state.selected){try{await edit('/split',{assetId:state.selected.id,mode:'line',line:{x1:start.x,y1:start.y,x2:end.x,y2:end.y,width:Math.max(1,Math.round(+$('#brushSize').value/5))}})}catch(err){message(err.message)}}draw()}
function draw(){const c=$('#stage'),wrap=c.parentElement;c.width=Math.max(600,wrap.clientWidth);c.height=Math.max(380,wrap.clientHeight);const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);if(!state.image)return;const t=transform();x.drawImage(state.image,t.x,t.y,state.image.width*t.scale,state.image.height*t.scale);x.font='bold 13px system-ui';for(const a of state.assets){x.strokeStyle=a.id===state.selected?.id?'#0875d4':a.status==='needs-review'?'#f07418':'#16a065';x.lineWidth=a.id===state.selected?.id?3:2;x.strokeRect(t.x+a.x*t.scale,t.y+a.y*t.scale,a.width*t.scale,a.height*t.scale);x.fillStyle=x.strokeStyle;x.fillText(String(a.index),t.x+a.x*t.scale+3,t.y+a.y*t.scale+14)}if(state.stroke.length){x.strokeStyle=state.tool==='erase'?'#ef3340aa':'#16a065aa';x.lineWidth=+$('#brushSize').value*t.scale;x.lineCap='round';x.beginPath();state.stroke.forEach((p,i)=>i?x.lineTo(t.x+p.x*t.scale,t.y+p.y*t.scale):x.moveTo(t.x+p.x*t.scale,t.y+p.y*t.scale));x.stroke()}if(state.tool==='split'&&state.drag){x.strokeStyle='#ef3340';x.lineWidth=3;x.beginPath();x.moveTo(t.x+state.drag.start.x*t.scale,t.y+state.drag.start.y*t.scale);x.lineTo(t.x+state.drag.last.x*t.scale,t.y+state.drag.last.y*t.scale);x.stroke()}}
async function edit(path,payload){try{state.task=await api(`/api/asset-extraction/tasks/${state.task.task_id}${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,revision:revision()})});await loadWorkspace()}catch(err){message(err.message);throw err}}
async function applyStroke(){if(!state.selected||!state.stroke.length)return message('请先在原图上绘制画笔');await api(`/api/asset-extraction/tasks/${state.task.task_id}/assets/${state.selected.id}/mask`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:revision(),mode:state.tool,strokes:[{points:state.stroke,size:+$('#brushSize').value,hardness:+$('#hardness').value,feather:+$('#feather').value}]})}).then(async t=>{state.task=t;state.stroke=[];await loadWorkspace()}).catch(e=>message(e.message))}
async function saveBbox(){if(!state.selected)return;try{state.task=await api(`/api/asset-extraction/tasks/${state.task.task_id}/assets/${state.selected.id}/bbox`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:revision(),bbox:{x:+$('#bx').value,y:+$('#by').value,width:+$('#bw').value,height:+$('#bh').value}})});await loadWorkspace()}catch(e){message(e.message)}}
async function merge(){const ids=$$('.asset-card input:checked').map(x=>x.closest('.asset-card').dataset.id);if(ids.length<2)return message('至少勾选两个素材');await edit('/merge',{assetIds:ids})}
async function removeAsset(){if(!state.selected)return;try{state.task=await api(`/api/asset-extraction/tasks/${state.task.task_id}/assets/${state.selected.id}/delete`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:revision()})});state.selected=null;await loadWorkspace()}catch(e){message(e.message)}}
async function move(delta){if(!state.selected)return;const ids=state.assets.map(a=>a.id),i=ids.indexOf(state.selected.id),j=Math.max(0,Math.min(ids.length-1,i+delta));[ids[i],ids[j]]=[ids[j],ids[i]];await edit('/sort',{assetIds:ids})}
async function rename(){if(!state.selected)return;try{state.task=await api(`/api/asset-extraction/tasks/${state.task.task_id}/assets/${state.selected.id}/name`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:revision(),name:$('#renameInput').value})});await loadWorkspace()}catch(e){message(e.message)}}
async function exportFiles(){try{const r=await api(`/api/asset-extraction/tasks/${state.task.task_id}/export`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({includeZip:$('#exportZip').checked})});const links=[['JSON',r.metadataJsonUrl],['CSV',r.metadataCsvUrl],['标注图',r.annotatedUrl]];if(r.downloadUrl)links.push(['ZIP',r.downloadUrl]);$('#downloads').innerHTML=links.map(([n,u])=>`<a href="${u}">${n} 下载</a>`).join('');message('导出已更新',true)}catch(e){message(e.message)}}
init();
